version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    ports:
      - 8080:8080
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    volumes:
      - .docker/data.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  activemq:
    image: rmohr/activemq:5.10.0
    container_name: activemq
    ports:
      - "61616:61616" # broker (amq:amq)
      - "8161:8161"   # web    (admin:admin)

